### ISSUE TITLE
Plugin mirror in china

### ISSUE THREAD

**Issue by yogeek** [grafana-operator/grafana_plugins_init#3]
Hello, 

I installed Grafana operator on a K8S cluster in AWS China and then install this dashboard CR to initialize some plugins used in future dashboards :
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: empty-dashboard
  labels:
    app: grafana
    monitoring.discovery.dashboards: "true"
spec:
  json: |
    {
      "id": null,
      "title": "Empty Dashboard",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "hideControls": false,
      "graphTooltip": 1,
      "panels": [],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "time_options": [],
        "refresh_intervals": []
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "refresh": "5s",
      "schemaVersion": 17,
      "version": 0,
      "links": []
    }
  name: empty-dashboard.json
  plugins:
  - name: "grafana-piechart-panel"
    version: "1.5.0"
  - name: "camptocamp-prometheus-alertmanager-datasource"
    version: "0.0.8"
  - name: "grafana-worldmap-panel"
    version: "0.3.2"
  - name: "simpod-json-datasource"
    version: "0.2.0"
  - name: "agenty-flowcharting-panel"
    version: "0.8.1"
```

But the initialization was so long I thought there was an error with the grafana server...
I then checked the different plugins download time from a China server and it appears that it was indeed the cause of the problem : more than 8 minutes to download these 5 plugins.
(the main culprit being "agenty-flowcharting-panel" which took 6 min...)

My question is : is there any mirror for grafana plugin I could use in China please ?
And is there a way to configure grafana to use another download plugin server in the first place ?

**Comment by NissesSenap** [comment]
Looking at the answer in grafana I think we can close this issue.
